[package]
name = "midway"
authors.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
enum-iterator = "2.1.0"
rand = "0.8.5"
random-pick = "1.2.16"
