[package]
name = "enterprise"
authors.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
eframe = "0.28.1"
egui_extras = { version = "0.28.1", features = ["all_loaders"] }
